---
- name: deployment scripts
  hosts: all
  user: ec2-user
  gather_facts: true
  vars:
    add_to_asg: true
    replace_all: true
  pre_tasks:

  tasks:
    - name: Print some debug information 
      vars: 
        msg: |
            Module Variables ("vars"):
            --------------------------------
            {{ vars | to_nice_json }} 
    
            Environment Variables ("environment"):
            --------------------------------
            {{ environment | to_nice_json }} 
    
            GROUP NAMES Variables ("group_names"):
            --------------------------------
            {{ group_names | to_nice_json }}
    
            GROUPS Variables ("groups"):
            --------------------------------
            {{ groups | to_nice_json }}
    
            HOST Variables ("hostvars"):
            --------------------------------
            {{ hostvars | to_nice_json }} 
    
      debug: 
        msg: "{{ msg.split('\n') }}"       
      tags: debug_info
  
   